// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kcl_event.proto

package com.kcl.event.grpc;

public interface EventResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kcl.event.grpc.EventResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * e.g., "ACK", "ERROR", "RECEIVED"
   * </pre>
   *
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * e.g., "ACK", "ERROR", "RECEIVED"
   * </pre>
   *
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
