// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kcl_event.proto

package com.kcl.event.grpc;

public final class KclEvent {
  private KclEvent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kcl_event_grpc_EventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kcl_event_grpc_EventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kcl_event_grpc_EventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kcl_event_grpc_EventResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017kcl_event.proto\022\022com.kcl.event.grpc\"\202\001" +
      "\n\014EventRequest\022\022\n\nevent_type\030\001 \001(\t\022\020\n\010re" +
      "alm_id\030\002 \001(\t\022\021\n\tclient_id\030\003 \001(\t\022\017\n\007user_" +
      "id\030\004 \001(\t\022\022\n\nip_address\030\005 \001(\t\022\024\n\014payload_" +
      "json\030\006 \001(\t\"\037\n\rEventResponse\022\016\n\006status\030\001 " +
      "\001(\t2d\n\014EventService\022T\n\013StreamEvent\022 .com" +
      ".kcl.event.grpc.EventRequest\032!.com.kcl.e" +
      "vent.grpc.EventResponse(\001B\026\n\022com.kcl.eve" +
      "nt.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_kcl_event_grpc_EventRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kcl_event_grpc_EventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kcl_event_grpc_EventRequest_descriptor,
        new java.lang.String[] { "EventType", "RealmId", "ClientId", "UserId", "IpAddress", "PayloadJson", });
    internal_static_com_kcl_event_grpc_EventResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_kcl_event_grpc_EventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kcl_event_grpc_EventResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
