# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kcl_event.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'kcl_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fkcl_event.proto\x12\x12\x63om.kcl.event.grpc\"\x82\x01\n\x0c\x45ventRequest\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x10\n\x08realm_id\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12\x12\n\nip_address\x18\x05 \x01(\t\x12\x14\n\x0cpayload_json\x18\x06 \x01(\t\"\x1f\n\rEventResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2d\n\x0c\x45ventService\x12T\n\x0bStreamEvent\x12 .com.kcl.event.grpc.EventRequest\x1a!.com.kcl.event.grpc.EventResponse(\x01\x42\x16\n\x12\x63om.kcl.event.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kcl_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.kcl.event.grpcP\001'
  _globals['_EVENTREQUEST']._serialized_start=40
  _globals['_EVENTREQUEST']._serialized_end=170
  _globals['_EVENTRESPONSE']._serialized_start=172
  _globals['_EVENTRESPONSE']._serialized_end=203
  _globals['_EVENTSERVICE']._serialized_start=205
  _globals['_EVENTSERVICE']._serialized_end=305
# @@protoc_insertion_point(module_scope)
